printWidth: 80
tabWidth: 2
useTabs: false

semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false

trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always

proseWrap: always
htmlWhitespaceSensitivity: ignore

# PHP
braceStyle: 1tbs
phpVersion: "7.2"
trailingCommaPHP: all

overrides:
  - files: composer.json
    options:
      tabWidth: 4
